project:
  type: book
  output-dir: docs

book:
  title: "MKTG212 Labs"
  author: "Ahmad Daryanto"
  date: 11/23/2025
  date-format: long
  chapters:
    - index.qmd
    - lab1.qmd
    - lab2.qmd
    - lab3.qmd
    - lab4.qmd
    - lab5.qmd
   

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual